### PR TITLE
Update spi_flash_memory to add NAND support and numbered payload.

### PR DESCRIPTION
**Pull request by cHemingway**
Support for Micron MT29F 60 series NAND SPI flash.
I have tested most commands, apart from dual/quad.
Also added an option to enumarate each data byte, useful with long payloads.

### CODE REVIEW

**Comment by cHemingway** [comment]
### Known issues:

- [ ] on_build_demo_signals() does not work with NAND flash type

**Comment by cHemingway** [comment]
Hey, any thoughts on this pull request? Anything I can do to improve it?

**Comment by ikalogic** [comment]
Thank you very much @cHemingway ! 
I would love to hear about your experience with this JavaScript API, and how hard (or easy) it was to use it?

**Comment by cHemingway** [comment]
Hi @ikalogic !

Thanks! 
I have [another branch](https://github.com/cHemingway/ScanaStudio-scripts-v3/tree/spi_flash_packet_view) with packet supported added (works with NOR too), I will check if it is up to scratch for a pull request.

Its been a bit of a while, so I might have forgotten some things, but generally my thoughts on the JS API are that is is perfectly servicable, though not too friendly for beginners. 

### GUI Issues

- Once I have created a dec_item or packet_item (I have another branch with packet support), I can't change it later. It would be nice to be able to access it later to change the color if I parse the packet further and find an error. Otherwise, I need to store a stack of items and pop them on/off as needed. A simple way to do this would be to have `ScanaStudio.packet_view_add_packet` or `ScanaStudio.dec_item_new` return an object with attributes/functions to change the properties, I think this would simplify the logic a lot.

- The interface to read gui values, `ScanaStudio.gui_get_value("name")` is a bit long to type, which is presumable why the original script sets a lot of global variables instead via [read_gui_values](https://github.com/ikalogic/ScanaStudio-scripts-v3/blob/68f874104382110806c636c66fc679347d4f0539/spi_flash_memory.js#L93-L108)
Maybe a function to get them all in an object, indexed by ID? e.g:
```js
g_args = ScanaStudio.gui_get_all_values();
g_args["cpol"];          // Gets cpol argument
g_args["flash_type"];    // Gets flash type
g_args["unknown_arg"];   // returns undefined
// And therefore I can write
if (g_args["my_value"] != null) {
   ScanaStudio.console_info_msg("Got my_value: " + g_args["my_value"]);
}
```

- If I don't implement the packet view, navigating between data sent with big gaps in between requires me to zoom out, scroll along, and zoom back in. With the packet view, I still need to double click on each packet to see it, the arrow keys move through the list of packets but `<enter>` does nothing.  It would be nice if I could use the arrow keys to go to the next/previous packet or group of signals?

### SPI Decoder Issues
- If I have spurious transitions on the edge of the clock (normally as I have set the voltage level too high, 3.3V instead of 1.8V) the SPI decoder seems to treat these as valid and so clocks in "wrong" data. In a very large transaction, it can be hard to detect this happened! Some sort of noise filtering or oversampling for the SPI decoder would be ideal.

### General Language Experience
- Live reload of the code when I press the refresh button in ScanaStudio is very nice, please keep this.
- I used Electron, which worked well for the autocompletion, a very useful plugin!
- What version of JavaScript is this? EMCA5? It would be good to know which features I can use.
- With more complex logic, only having one file, and debugging everything with print statements is a bit tricky, especially as JS doesn't do many compile time errors, and likes to print things like `[object Object]`. Some more console functions e.g. Google Chrome's [`console.dir(object)`](https://developers.google.com/web/tools/chrome-devtools/debug/console/console-reference#dir) could be nice?

**Comment by ikalogic** [comment]
@cHemingway Thank you very much for this detailed response.

Your ideas are excellent, and we will implement them, alongside other features being added.

**Pull request merged**
